<a href="https://colab.research.google.com/github/Ajaykrishna5445/web-progaramming/blob/main/00_pytroch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pytorch_fundamentals:
Resource note:https://www.learnpytorch.io/00_pytorch_fundamentals/


Any doubt:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


## introduction to Tensors
### creating Tensors
Pytorch tensors are created using torch.Tensor() -= https://pytorch.org/docs/stable/tensors.html

In [7]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.item()
# Get tensor back as Python int

7

In [10]:
scalar.ndim

0

In [13]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
# To identify how many diamensions
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [22]:
# createing MATRIX
MATRIX=torch.tensor([[7,8],
                     [3,4]])
MATRIX


tensor([[7, 8],
        [3, 4]])

In [23]:
MATRIX.ndim

2

In [38]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,7],
                      [6,7,8],
                      [6,7,8],
                   [7,8,3],
                      [3,0,5],
                      [4,6,2],
                      [3,7,3],
                      [2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 4, 7],
         [6, 7, 8],
         [6, 7, 8],
         [7, 8, 3],
         [3, 0, 5],
         [4, 6, 2],
         [3, 7, 3],
         [2, 4, 5]]])

In [39]:
TENSOR.ndim

3

In [40]:
TENSOR.shape

torch.Size([1, 9, 3])

In [43]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 7],
        [6, 7, 8],
        [6, 7, 8],
        [7, 8, 3],
        [3, 0, 5],
        [4, 6, 2],
        [3, 7, 3],
        [2, 4, 5]])

### Random Tensors
why random tensors?
 Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data...


 Start with random numbers  _> look at data  _> update random numbers  _> look at data  _> update random numbers..

 Torch Random Tensors:https://pytorch.org/docs/stable/generated/torch.rand.html

In [52]:
# create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8567, 0.1212, 0.9429, 0.9015],
        [0.0456, 0.6815, 0.5012, 0.2335],
        [0.8383, 0.3407, 0.9582, 0.4084]])

In [62]:
# Create a random tensor with similar shape to an image tensor
random_size_image_tensor=torch.rand(size=(234,234,3)) # Height,width,color channle (R,G,B)
random_size_image_tensor.shape,random_size_image_tensor.ndim

(torch.Size([234, 234, 3]), 3)